//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.goldinfo.yeexing.com")]
    public partial class MalformedURLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.goldinfo.yeexing.com")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.goldinfo.yeexing.com")]
    public partial class DocumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.goldinfo.yeexing.com", ConfigurationName="ServiceReference.IBEServicePortType")]
    public interface IBEServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.RefuseOutTicketResponse RefuseOutTicket(ConsoleApplication1.ServiceReference.RefuseOutTicket request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefuseOutTicketResponse> RefuseOutTicketAsync(ConsoleApplication1.ServiceReference.RefuseOutTicket request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.RefundTicketResponse RefundTicket(ConsoleApplication1.ServiceReference.RefundTicket request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefundTicketResponse> RefundTicketAsync(ConsoleApplication1.ServiceReference.RefundTicket request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfoResponse QueryRefundHisDetailInfo(ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfoResponse> QueryRefundHisDetailInfoAsync(ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.QueryRequireOrderResponse QueryRequireOrder(ConsoleApplication1.ServiceReference.QueryRequireOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRequireOrderResponse> QueryRequireOrderAsync(ConsoleApplication1.ServiceReference.QueryRequireOrder request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference.MalformedURLException), Action="", Name="MalformedURLException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference.IOException), Action="", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference.DocumentException), Action="", Name="DocumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.RefundAccountResponse RefundAccount(ConsoleApplication1.ServiceReference.RefundAccount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefundAccountResponse> RefundAccountAsync(ConsoleApplication1.ServiceReference.RefundAccount request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.QueryOrderInfoResponse QueryOrderInfo(ConsoleApplication1.ServiceReference.QueryOrderInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryOrderInfoResponse> QueryOrderInfoAsync(ConsoleApplication1.ServiceReference.QueryOrderInfo request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.OutTicketsResponse OutTickets(ConsoleApplication1.ServiceReference.OutTickets request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.OutTicketsResponse> OutTicketsAsync(ConsoleApplication1.ServiceReference.OutTickets request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.QueryRequireRefundOrderResponse QueryRequireRefundOrder(ConsoleApplication1.ServiceReference.QueryRequireRefundOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRequireRefundOrderResponse> QueryRequireRefundOrderAsync(ConsoleApplication1.ServiceReference.QueryRequireRefundOrder request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.ModifyRefuseTicketStateResponse ModifyRefuseTicketState(ConsoleApplication1.ServiceReference.ModifyRefuseTicketState request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.ModifyRefuseTicketStateResponse> ModifyRefuseTicketStateAsync(ConsoleApplication1.ServiceReference.ModifyRefuseTicketState request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.RefuseRefundTicketResponse RefuseRefundTicket(ConsoleApplication1.ServiceReference.RefuseRefundTicket request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefuseRefundTicketResponse> RefuseRefundTicketAsync(ConsoleApplication1.ServiceReference.RefuseRefundTicket request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.SplitAccountResponse SplitAccount(ConsoleApplication1.ServiceReference.SplitAccount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.SplitAccountResponse> SplitAccountAsync(ConsoleApplication1.ServiceReference.SplitAccount request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.ModifyOutTicketStateResponse ModifyOutTicketState(ConsoleApplication1.ServiceReference.ModifyOutTicketState request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.ModifyOutTicketStateResponse> ModifyOutTicketStateAsync(ConsoleApplication1.ServiceReference.ModifyOutTicketState request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfoResponse QueryRefundHisOrderInfo(ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfoResponse> QueryRefundHisOrderInfoAsync(ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefuseOutTicket", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefuseOutTicket {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordDetid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordDetname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refuseMemo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public RefuseOutTicket() {
        }
        
        public RefuseOutTicket(string userName, string orderId, string ordDetid, string ordDetname, string refuseMemo, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.ordDetid = ordDetid;
            this.ordDetname = ordDetname;
            this.refuseMemo = refuseMemo;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefuseOutTicketResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefuseOutTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public RefuseOutTicketResponse() {
        }
        
        public RefuseOutTicketResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefundTicket", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefundTicket {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refundType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public RefundTicket() {
        }
        
        public RefundTicket(string userName, string orderId, string returnDetail, string refundType, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.returnDetail = returnDetail;
            this.refundType = refundType;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefundTicketResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefundTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public RefundTicketResponse() {
        }
        
        public RefundTicketResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRefundHisDetailInfo", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRefundHisDetailInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordAirID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public QueryRefundHisDetailInfo() {
        }
        
        public QueryRefundHisDetailInfo(string userName, string orderId, string ordAirID, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.ordAirID = ordAirID;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRefundHisDetailInfoResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRefundHisDetailInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryRefundHisDetailInfoResponse() {
        }
        
        public QueryRefundHisDetailInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRequireOrder", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRequireOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public QueryRequireOrder() {
        }
        
        public QueryRequireOrder(string userName, string orderId, string pnr, string ordState, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.pnr = pnr;
            this.ordState = ordState;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRequireOrderResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRequireOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryRequireOrderResponse() {
        }
        
        public QueryRequireOrderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefundAccount", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefundAccount {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderid;
        
        public RefundAccount() {
        }
        
        public RefundAccount(string orderid) {
            this.orderid = orderid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefundAccountResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefundAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public RefundAccountResponse() {
        }
        
        public RefundAccountResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryOrderInfo", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryOrderInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordAirID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordDetname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordAirComp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordhomeport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orddestport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enddate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public QueryOrderInfo() {
        }
        
        public QueryOrderInfo(string userName, string orderId, string pnr, string ordAirID, string ordDetname, string ordAirComp, string ordhomeport, string orddestport, string ordState, string ordType, string startdate, string enddate, string page, string count, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.pnr = pnr;
            this.ordAirID = ordAirID;
            this.ordDetname = ordDetname;
            this.ordAirComp = ordAirComp;
            this.ordhomeport = ordhomeport;
            this.orddestport = orddestport;
            this.ordState = ordState;
            this.ordType = ordType;
            this.startdate = startdate;
            this.enddate = enddate;
            this.page = page;
            this.count = count;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryOrderInfoResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryOrderInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryOrderInfoResponse() {
        }
        
        public QueryOrderInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OutTickets", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class OutTickets {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orddetid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrdDetname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrdAirID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Newpnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public OutTickets() {
        }
        
        public OutTickets(string userName, string orderId, string orddetid, string OrdDetname, string OrdAirID, string Newpnr, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.orddetid = orddetid;
            this.OrdDetname = OrdDetname;
            this.OrdAirID = OrdAirID;
            this.Newpnr = Newpnr;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OutTicketsResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class OutTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public OutTicketsResponse() {
        }
        
        public OutTicketsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRequireRefundOrder", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRequireRefundOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refundType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isWaitAuditQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aircomp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passengerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordAirID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enddate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderParam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public QueryRequireRefundOrder() {
        }
        
        public QueryRequireRefundOrder(string userName, string refundType, string isWaitAuditQuery, string aircomp, string passengerName, string orderId, string ordAirID, string pnr, string enddate, string orderParam, string orderMode, string sign) {
            this.userName = userName;
            this.refundType = refundType;
            this.isWaitAuditQuery = isWaitAuditQuery;
            this.aircomp = aircomp;
            this.passengerName = passengerName;
            this.orderId = orderId;
            this.ordAirID = ordAirID;
            this.pnr = pnr;
            this.enddate = enddate;
            this.orderParam = orderParam;
            this.orderMode = orderMode;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRequireRefundOrderResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRequireRefundOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryRequireRefundOrderResponse() {
        }
        
        public QueryRequireRefundOrderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyRefuseTicketState", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class ModifyRefuseTicketState {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string goldid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public ModifyRefuseTicketState() {
        }
        
        public ModifyRefuseTicketState(string userName, string orderId, string goldid, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.goldid = goldid;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyRefuseTicketStateResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class ModifyRefuseTicketStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ModifyRefuseTicketStateResponse() {
        }
        
        public ModifyRefuseTicketStateResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefuseRefundTicket", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefuseRefundTicket {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refusememo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public RefuseRefundTicket() {
        }
        
        public RefuseRefundTicket(string userName, string orderId, string refusememo, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.refusememo = refusememo;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefuseRefundTicketResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class RefuseRefundTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public RefuseRefundTicketResponse() {
        }
        
        public RefuseRefundTicketResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SplitAccount", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class SplitAccount {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string goldid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public SplitAccount() {
        }
        
        public SplitAccount(string userName, string orderId, string goldid, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.goldid = goldid;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SplitAccountResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class SplitAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public SplitAccountResponse() {
        }
        
        public SplitAccountResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyOutTicketState", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class ModifyOutTicketState {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orddetid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrdDetname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrdAirID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Newpnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public ModifyOutTicketState() {
        }
        
        public ModifyOutTicketState(string userName, string orderId, string orddetid, string OrdDetname, string OrdAirID, string Newpnr, string sign) {
            this.userName = userName;
            this.orderId = orderId;
            this.orddetid = orddetid;
            this.OrdDetname = OrdDetname;
            this.OrdAirID = OrdAirID;
            this.Newpnr = Newpnr;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyOutTicketStateResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class ModifyOutTicketStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ModifyOutTicketStateResponse() {
        }
        
        public ModifyOutTicketStateResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRefundHisOrderInfo", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRefundHisOrderInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passengerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enddate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordAirID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        public QueryRefundHisOrderInfo() {
        }
        
        public QueryRefundHisOrderInfo(string userName, string passengerName, string startdate, string enddate, string ordAirID, string page, string count, string sign) {
            this.userName = userName;
            this.passengerName = passengerName;
            this.startdate = startdate;
            this.enddate = enddate;
            this.ordAirID = ordAirID;
            this.page = page;
            this.count = count;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRefundHisOrderInfoResponse", WrapperNamespace="http://service.goldinfo.yeexing.com", IsWrapped=true)]
    public partial class QueryRefundHisOrderInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.goldinfo.yeexing.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QueryRefundHisOrderInfoResponse() {
        }
        
        public QueryRefundHisOrderInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBEServicePortTypeChannel : ConsoleApplication1.ServiceReference.IBEServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BEServicePortTypeClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference.IBEServicePortType>, ConsoleApplication1.ServiceReference.IBEServicePortType {
        
        public BEServicePortTypeClient() {
        }
        
        public BEServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BEServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BEServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BEServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.RefuseOutTicketResponse ConsoleApplication1.ServiceReference.IBEServicePortType.RefuseOutTicket(ConsoleApplication1.ServiceReference.RefuseOutTicket request) {
            return base.Channel.RefuseOutTicket(request);
        }
        
        public string RefuseOutTicket(string userName, string orderId, string ordDetid, string ordDetname, string refuseMemo, string sign) {
            ConsoleApplication1.ServiceReference.RefuseOutTicket inValue = new ConsoleApplication1.ServiceReference.RefuseOutTicket();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.ordDetid = ordDetid;
            inValue.ordDetname = ordDetname;
            inValue.refuseMemo = refuseMemo;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.RefuseOutTicketResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefuseOutTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefuseOutTicketResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.RefuseOutTicketAsync(ConsoleApplication1.ServiceReference.RefuseOutTicket request) {
            return base.Channel.RefuseOutTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefuseOutTicketResponse> RefuseOutTicketAsync(string userName, string orderId, string ordDetid, string ordDetname, string refuseMemo, string sign) {
            ConsoleApplication1.ServiceReference.RefuseOutTicket inValue = new ConsoleApplication1.ServiceReference.RefuseOutTicket();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.ordDetid = ordDetid;
            inValue.ordDetname = ordDetname;
            inValue.refuseMemo = refuseMemo;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefuseOutTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.RefundTicketResponse ConsoleApplication1.ServiceReference.IBEServicePortType.RefundTicket(ConsoleApplication1.ServiceReference.RefundTicket request) {
            return base.Channel.RefundTicket(request);
        }
        
        public string RefundTicket(string userName, string orderId, string returnDetail, string refundType, string sign) {
            ConsoleApplication1.ServiceReference.RefundTicket inValue = new ConsoleApplication1.ServiceReference.RefundTicket();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.returnDetail = returnDetail;
            inValue.refundType = refundType;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.RefundTicketResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefundTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefundTicketResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.RefundTicketAsync(ConsoleApplication1.ServiceReference.RefundTicket request) {
            return base.Channel.RefundTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefundTicketResponse> RefundTicketAsync(string userName, string orderId, string returnDetail, string refundType, string sign) {
            ConsoleApplication1.ServiceReference.RefundTicket inValue = new ConsoleApplication1.ServiceReference.RefundTicket();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.returnDetail = returnDetail;
            inValue.refundType = refundType;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefundTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfoResponse ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRefundHisDetailInfo(ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo request) {
            return base.Channel.QueryRefundHisDetailInfo(request);
        }
        
        public string QueryRefundHisDetailInfo(string userName, string orderId, string ordAirID, string sign) {
            ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo inValue = new ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.ordAirID = ordAirID;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfoResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRefundHisDetailInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfoResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRefundHisDetailInfoAsync(ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo request) {
            return base.Channel.QueryRefundHisDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfoResponse> QueryRefundHisDetailInfoAsync(string userName, string orderId, string ordAirID, string sign) {
            ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo inValue = new ConsoleApplication1.ServiceReference.QueryRefundHisDetailInfo();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.ordAirID = ordAirID;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRefundHisDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.QueryRequireOrderResponse ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRequireOrder(ConsoleApplication1.ServiceReference.QueryRequireOrder request) {
            return base.Channel.QueryRequireOrder(request);
        }
        
        public string QueryRequireOrder(string userName, string orderId, string pnr, string ordState, string sign) {
            ConsoleApplication1.ServiceReference.QueryRequireOrder inValue = new ConsoleApplication1.ServiceReference.QueryRequireOrder();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.pnr = pnr;
            inValue.ordState = ordState;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.QueryRequireOrderResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRequireOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRequireOrderResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRequireOrderAsync(ConsoleApplication1.ServiceReference.QueryRequireOrder request) {
            return base.Channel.QueryRequireOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRequireOrderResponse> QueryRequireOrderAsync(string userName, string orderId, string pnr, string ordState, string sign) {
            ConsoleApplication1.ServiceReference.QueryRequireOrder inValue = new ConsoleApplication1.ServiceReference.QueryRequireOrder();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.pnr = pnr;
            inValue.ordState = ordState;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRequireOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.RefundAccountResponse ConsoleApplication1.ServiceReference.IBEServicePortType.RefundAccount(ConsoleApplication1.ServiceReference.RefundAccount request) {
            return base.Channel.RefundAccount(request);
        }
        
        public string RefundAccount(string orderid) {
            ConsoleApplication1.ServiceReference.RefundAccount inValue = new ConsoleApplication1.ServiceReference.RefundAccount();
            inValue.orderid = orderid;
            ConsoleApplication1.ServiceReference.RefundAccountResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefundAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefundAccountResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.RefundAccountAsync(ConsoleApplication1.ServiceReference.RefundAccount request) {
            return base.Channel.RefundAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefundAccountResponse> RefundAccountAsync(string orderid) {
            ConsoleApplication1.ServiceReference.RefundAccount inValue = new ConsoleApplication1.ServiceReference.RefundAccount();
            inValue.orderid = orderid;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefundAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.QueryOrderInfoResponse ConsoleApplication1.ServiceReference.IBEServicePortType.QueryOrderInfo(ConsoleApplication1.ServiceReference.QueryOrderInfo request) {
            return base.Channel.QueryOrderInfo(request);
        }
        
        public string QueryOrderInfo(string userName, string orderId, string pnr, string ordAirID, string ordDetname, string ordAirComp, string ordhomeport, string orddestport, string ordState, string ordType, string startdate, string enddate, string page, string count, string sign) {
            ConsoleApplication1.ServiceReference.QueryOrderInfo inValue = new ConsoleApplication1.ServiceReference.QueryOrderInfo();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.pnr = pnr;
            inValue.ordAirID = ordAirID;
            inValue.ordDetname = ordDetname;
            inValue.ordAirComp = ordAirComp;
            inValue.ordhomeport = ordhomeport;
            inValue.orddestport = orddestport;
            inValue.ordState = ordState;
            inValue.ordType = ordType;
            inValue.startdate = startdate;
            inValue.enddate = enddate;
            inValue.page = page;
            inValue.count = count;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.QueryOrderInfoResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryOrderInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryOrderInfoResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.QueryOrderInfoAsync(ConsoleApplication1.ServiceReference.QueryOrderInfo request) {
            return base.Channel.QueryOrderInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryOrderInfoResponse> QueryOrderInfoAsync(string userName, string orderId, string pnr, string ordAirID, string ordDetname, string ordAirComp, string ordhomeport, string orddestport, string ordState, string ordType, string startdate, string enddate, string page, string count, string sign) {
            ConsoleApplication1.ServiceReference.QueryOrderInfo inValue = new ConsoleApplication1.ServiceReference.QueryOrderInfo();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.pnr = pnr;
            inValue.ordAirID = ordAirID;
            inValue.ordDetname = ordDetname;
            inValue.ordAirComp = ordAirComp;
            inValue.ordhomeport = ordhomeport;
            inValue.orddestport = orddestport;
            inValue.ordState = ordState;
            inValue.ordType = ordType;
            inValue.startdate = startdate;
            inValue.enddate = enddate;
            inValue.page = page;
            inValue.count = count;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryOrderInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.OutTicketsResponse ConsoleApplication1.ServiceReference.IBEServicePortType.OutTickets(ConsoleApplication1.ServiceReference.OutTickets request) {
            return base.Channel.OutTickets(request);
        }
        
        public string OutTickets(string userName, string orderId, string orddetid, string OrdDetname, string OrdAirID, string Newpnr, string sign) {
            ConsoleApplication1.ServiceReference.OutTickets inValue = new ConsoleApplication1.ServiceReference.OutTickets();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.orddetid = orddetid;
            inValue.OrdDetname = OrdDetname;
            inValue.OrdAirID = OrdAirID;
            inValue.Newpnr = Newpnr;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.OutTicketsResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).OutTickets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.OutTicketsResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.OutTicketsAsync(ConsoleApplication1.ServiceReference.OutTickets request) {
            return base.Channel.OutTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.OutTicketsResponse> OutTicketsAsync(string userName, string orderId, string orddetid, string OrdDetname, string OrdAirID, string Newpnr, string sign) {
            ConsoleApplication1.ServiceReference.OutTickets inValue = new ConsoleApplication1.ServiceReference.OutTickets();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.orddetid = orddetid;
            inValue.OrdDetname = OrdDetname;
            inValue.OrdAirID = OrdAirID;
            inValue.Newpnr = Newpnr;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).OutTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.QueryRequireRefundOrderResponse ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRequireRefundOrder(ConsoleApplication1.ServiceReference.QueryRequireRefundOrder request) {
            return base.Channel.QueryRequireRefundOrder(request);
        }
        
        public string QueryRequireRefundOrder(string userName, string refundType, string isWaitAuditQuery, string aircomp, string passengerName, string orderId, string ordAirID, string pnr, string enddate, string orderParam, string orderMode, string sign) {
            ConsoleApplication1.ServiceReference.QueryRequireRefundOrder inValue = new ConsoleApplication1.ServiceReference.QueryRequireRefundOrder();
            inValue.userName = userName;
            inValue.refundType = refundType;
            inValue.isWaitAuditQuery = isWaitAuditQuery;
            inValue.aircomp = aircomp;
            inValue.passengerName = passengerName;
            inValue.orderId = orderId;
            inValue.ordAirID = ordAirID;
            inValue.pnr = pnr;
            inValue.enddate = enddate;
            inValue.orderParam = orderParam;
            inValue.orderMode = orderMode;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.QueryRequireRefundOrderResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRequireRefundOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRequireRefundOrderResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRequireRefundOrderAsync(ConsoleApplication1.ServiceReference.QueryRequireRefundOrder request) {
            return base.Channel.QueryRequireRefundOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRequireRefundOrderResponse> QueryRequireRefundOrderAsync(string userName, string refundType, string isWaitAuditQuery, string aircomp, string passengerName, string orderId, string ordAirID, string pnr, string enddate, string orderParam, string orderMode, string sign) {
            ConsoleApplication1.ServiceReference.QueryRequireRefundOrder inValue = new ConsoleApplication1.ServiceReference.QueryRequireRefundOrder();
            inValue.userName = userName;
            inValue.refundType = refundType;
            inValue.isWaitAuditQuery = isWaitAuditQuery;
            inValue.aircomp = aircomp;
            inValue.passengerName = passengerName;
            inValue.orderId = orderId;
            inValue.ordAirID = ordAirID;
            inValue.pnr = pnr;
            inValue.enddate = enddate;
            inValue.orderParam = orderParam;
            inValue.orderMode = orderMode;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRequireRefundOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.ModifyRefuseTicketStateResponse ConsoleApplication1.ServiceReference.IBEServicePortType.ModifyRefuseTicketState(ConsoleApplication1.ServiceReference.ModifyRefuseTicketState request) {
            return base.Channel.ModifyRefuseTicketState(request);
        }
        
        public string ModifyRefuseTicketState(string userName, string orderId, string goldid, string sign) {
            ConsoleApplication1.ServiceReference.ModifyRefuseTicketState inValue = new ConsoleApplication1.ServiceReference.ModifyRefuseTicketState();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.goldid = goldid;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.ModifyRefuseTicketStateResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).ModifyRefuseTicketState(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.ModifyRefuseTicketStateResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.ModifyRefuseTicketStateAsync(ConsoleApplication1.ServiceReference.ModifyRefuseTicketState request) {
            return base.Channel.ModifyRefuseTicketStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.ModifyRefuseTicketStateResponse> ModifyRefuseTicketStateAsync(string userName, string orderId, string goldid, string sign) {
            ConsoleApplication1.ServiceReference.ModifyRefuseTicketState inValue = new ConsoleApplication1.ServiceReference.ModifyRefuseTicketState();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.goldid = goldid;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).ModifyRefuseTicketStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.RefuseRefundTicketResponse ConsoleApplication1.ServiceReference.IBEServicePortType.RefuseRefundTicket(ConsoleApplication1.ServiceReference.RefuseRefundTicket request) {
            return base.Channel.RefuseRefundTicket(request);
        }
        
        public string RefuseRefundTicket(string userName, string orderId, string refusememo, string sign) {
            ConsoleApplication1.ServiceReference.RefuseRefundTicket inValue = new ConsoleApplication1.ServiceReference.RefuseRefundTicket();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.refusememo = refusememo;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.RefuseRefundTicketResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefuseRefundTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefuseRefundTicketResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.RefuseRefundTicketAsync(ConsoleApplication1.ServiceReference.RefuseRefundTicket request) {
            return base.Channel.RefuseRefundTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.RefuseRefundTicketResponse> RefuseRefundTicketAsync(string userName, string orderId, string refusememo, string sign) {
            ConsoleApplication1.ServiceReference.RefuseRefundTicket inValue = new ConsoleApplication1.ServiceReference.RefuseRefundTicket();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.refusememo = refusememo;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).RefuseRefundTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.SplitAccountResponse ConsoleApplication1.ServiceReference.IBEServicePortType.SplitAccount(ConsoleApplication1.ServiceReference.SplitAccount request) {
            return base.Channel.SplitAccount(request);
        }
        
        public string SplitAccount(string userName, string orderId, string goldid, string sign) {
            ConsoleApplication1.ServiceReference.SplitAccount inValue = new ConsoleApplication1.ServiceReference.SplitAccount();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.goldid = goldid;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.SplitAccountResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).SplitAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.SplitAccountResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.SplitAccountAsync(ConsoleApplication1.ServiceReference.SplitAccount request) {
            return base.Channel.SplitAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.SplitAccountResponse> SplitAccountAsync(string userName, string orderId, string goldid, string sign) {
            ConsoleApplication1.ServiceReference.SplitAccount inValue = new ConsoleApplication1.ServiceReference.SplitAccount();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.goldid = goldid;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).SplitAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.ModifyOutTicketStateResponse ConsoleApplication1.ServiceReference.IBEServicePortType.ModifyOutTicketState(ConsoleApplication1.ServiceReference.ModifyOutTicketState request) {
            return base.Channel.ModifyOutTicketState(request);
        }
        
        public string ModifyOutTicketState(string userName, string orderId, string orddetid, string OrdDetname, string OrdAirID, string Newpnr, string sign) {
            ConsoleApplication1.ServiceReference.ModifyOutTicketState inValue = new ConsoleApplication1.ServiceReference.ModifyOutTicketState();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.orddetid = orddetid;
            inValue.OrdDetname = OrdDetname;
            inValue.OrdAirID = OrdAirID;
            inValue.Newpnr = Newpnr;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.ModifyOutTicketStateResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).ModifyOutTicketState(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.ModifyOutTicketStateResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.ModifyOutTicketStateAsync(ConsoleApplication1.ServiceReference.ModifyOutTicketState request) {
            return base.Channel.ModifyOutTicketStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.ModifyOutTicketStateResponse> ModifyOutTicketStateAsync(string userName, string orderId, string orddetid, string OrdDetname, string OrdAirID, string Newpnr, string sign) {
            ConsoleApplication1.ServiceReference.ModifyOutTicketState inValue = new ConsoleApplication1.ServiceReference.ModifyOutTicketState();
            inValue.userName = userName;
            inValue.orderId = orderId;
            inValue.orddetid = orddetid;
            inValue.OrdDetname = OrdDetname;
            inValue.OrdAirID = OrdAirID;
            inValue.Newpnr = Newpnr;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).ModifyOutTicketStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfoResponse ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRefundHisOrderInfo(ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo request) {
            return base.Channel.QueryRefundHisOrderInfo(request);
        }
        
        public string QueryRefundHisOrderInfo(string userName, string passengerName, string startdate, string enddate, string ordAirID, string page, string count, string sign) {
            ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo inValue = new ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo();
            inValue.userName = userName;
            inValue.passengerName = passengerName;
            inValue.startdate = startdate;
            inValue.enddate = enddate;
            inValue.ordAirID = ordAirID;
            inValue.page = page;
            inValue.count = count;
            inValue.sign = sign;
            ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfoResponse retVal = ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRefundHisOrderInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfoResponse> ConsoleApplication1.ServiceReference.IBEServicePortType.QueryRefundHisOrderInfoAsync(ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo request) {
            return base.Channel.QueryRefundHisOrderInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfoResponse> QueryRefundHisOrderInfoAsync(string userName, string passengerName, string startdate, string enddate, string ordAirID, string page, string count, string sign) {
            ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo inValue = new ConsoleApplication1.ServiceReference.QueryRefundHisOrderInfo();
            inValue.userName = userName;
            inValue.passengerName = passengerName;
            inValue.startdate = startdate;
            inValue.enddate = enddate;
            inValue.ordAirID = ordAirID;
            inValue.page = page;
            inValue.count = count;
            inValue.sign = sign;
            return ((ConsoleApplication1.ServiceReference.IBEServicePortType)(this)).QueryRefundHisOrderInfoAsync(inValue);
        }
    }
}
