//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/", ConfigurationName="ServiceReference1.RefuseOrderForVenderService_1_0")]
    public interface RefuseOrderForVenderService_1_0 {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractLiantuoReply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractLiantuoRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference1.refuseOrderForVenderResponse refuseOrderForVender(ConsoleApplication1.ServiceReference1.refuseOrderForVender request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.refuseOrderForVenderResponse> refuseOrderForVenderAsync(ConsoleApplication1.ServiceReference1.refuseOrderForVender request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/")]
    public partial class refuseOrderForVenderRequest : abstractLiantuoRequest {
        
        private string officeNoField;
        
        private string orderNoField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private string refuseCauseField;
        
        private string refuseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string officeNo {
            get {
                return this.officeNoField;
            }
            set {
                this.officeNoField = value;
                this.RaisePropertyChanged("officeNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string refuseCause {
            get {
                return this.refuseCauseField;
            }
            set {
                this.refuseCauseField = value;
                this.RaisePropertyChanged("refuseCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string refuseCode {
            get {
                return this.refuseCodeField;
            }
            set {
                this.refuseCodeField = value;
                this.RaisePropertyChanged("refuseCode");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refuseOrderForVenderRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agencyCodeField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
                this.RaisePropertyChanged("agencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refuseOrderForVenderReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string returnStackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string returnStackTrace {
            get {
                return this.returnStackTraceField;
            }
            set {
                this.returnStackTraceField = value;
                this.RaisePropertyChanged("returnStackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/")]
    public partial class refuseOrderForVenderReply : abstractLiantuoReply {
        
        private string orderNoField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refuseOrderForVender", WrapperNamespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/", IsWrapped=true)]
    public partial class refuseOrderForVender {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.ServiceReference1.refuseOrderForVenderRequest request;
        
        public refuseOrderForVender() {
        }
        
        public refuseOrderForVender(ConsoleApplication1.ServiceReference1.refuseOrderForVenderRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refuseOrderForVenderResponse", WrapperNamespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/", IsWrapped=true)]
    public partial class refuseOrderForVenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://refuseOrderForVender.bcs.service.version1_0.webservice.model.ltips.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.ServiceReference1.refuseOrderForVenderReply @return;
        
        public refuseOrderForVenderResponse() {
        }
        
        public refuseOrderForVenderResponse(ConsoleApplication1.ServiceReference1.refuseOrderForVenderReply @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RefuseOrderForVenderService_1_0Channel : ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RefuseOrderForVenderService_1_0Client : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0>, ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0 {
        
        public RefuseOrderForVenderService_1_0Client() {
        }
        
        public RefuseOrderForVenderService_1_0Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RefuseOrderForVenderService_1_0Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RefuseOrderForVenderService_1_0Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RefuseOrderForVenderService_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.refuseOrderForVenderResponse ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0.refuseOrderForVender(ConsoleApplication1.ServiceReference1.refuseOrderForVender request) {
            return base.Channel.refuseOrderForVender(request);
        }
        
        public ConsoleApplication1.ServiceReference1.refuseOrderForVenderReply refuseOrderForVender(ConsoleApplication1.ServiceReference1.refuseOrderForVenderRequest request) {
            ConsoleApplication1.ServiceReference1.refuseOrderForVender inValue = new ConsoleApplication1.ServiceReference1.refuseOrderForVender();
            inValue.request = request;
            ConsoleApplication1.ServiceReference1.refuseOrderForVenderResponse retVal = ((ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0)(this)).refuseOrderForVender(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.refuseOrderForVenderResponse> ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0.refuseOrderForVenderAsync(ConsoleApplication1.ServiceReference1.refuseOrderForVender request) {
            return base.Channel.refuseOrderForVenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.refuseOrderForVenderResponse> refuseOrderForVenderAsync(ConsoleApplication1.ServiceReference1.refuseOrderForVenderRequest request) {
            ConsoleApplication1.ServiceReference1.refuseOrderForVender inValue = new ConsoleApplication1.ServiceReference1.refuseOrderForVender();
            inValue.request = request;
            return ((ConsoleApplication1.ServiceReference1.RefuseOrderForVenderService_1_0)(this)).refuseOrderForVenderAsync(inValue);
        }
    }
}
